/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageAirliners.ManageFlightSchedules;

import business.AirLiner;
import business.Airplane;
import business.Flight;
import business.FlightSchedule;
import business.Seat;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sweta Chowdhury
 */
public class CreateFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateFlightJPanel
     */
    private JPanel CardSequenceJPanel;
    private AirLiner airliner;
    private CardLayout layout;
    private TravelAgency travelAgency;
    private Airplane airplane;
    int size = 0;
    public CreateFlightJPanel(JPanel CardSequenceJPanel, TravelAgency travelAgency, AirLiner airliner, Airplane airplane) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airliner = airliner;
        this.airplane = airplane;
        layout = (CardLayout) CardSequenceJPanel.getLayout();
        this.travelAgency = travelAgency;
        jTxtTotalSeats.setText(Integer.toString(airplane.getPassengerCapacity()));
        size = (int) Math.sqrt(Double.parseDouble(jTxtTotalSeats.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTxtFlightNo = new javax.swing.JTextField();
        jTxtDepartureDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTxtDestination = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtSource = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtTotalSeats = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtDepartureTime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtArrivalDate = new javax.swing.JTextField();
        jTxtArrivalTime = new javax.swing.JTextField();

        jLabel6.setText("Destination               *");

        jLabel2.setText("Flight No                  *");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add Flight");

        jLabel4.setText("Source                     * ");

        jBtnSave.setText("Save");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Seats               *");

        jLabel5.setText("Departure Date          *");

        jTxtTotalSeats.setEditable(false);

        jLabel7.setText("Arrival Date               *");

        jLabel8.setText("Departure Time          *");

        jLabel9.setText("Arrival Time              *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFlightNo)
                                    .addComponent(jTxtSource))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jTxtDestination))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jTxtTotalSeats))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jTxtDepartureDate))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addComponent(jTxtArrivalDate)))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jTxtDepartureTime))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jTxtArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(251, 251, 251))
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jTxtDepartureDate, jTxtDestination, jTxtFlightNo, jTxtSource, jTxtTotalSeats});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTotalSeats)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtDepartureTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jTxtDepartureDate, jTxtDestination, jTxtFlightNo, jTxtSource, jTxtTotalSeats});

    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        // TODO add your handling code here:
        Boolean saveSuccessful = true;
        //Airplane airplane = airliner.addAirplane();
        FlightSchedule flightSchedule = airplane.getFlightSchedule();
        Flight flight = flightSchedule.addFlight();
                  
        if (jTxtFlightNo.getText().isEmpty() || jTxtSource.getText().isEmpty() || jTxtDestination.getText().isEmpty() || jTxtArrivalTime.getText().isEmpty() || jTxtArrivalDate.getText().isEmpty() || jTxtDepartureDate.getText().isEmpty() || jTxtDepartureTime.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "All (*) marked fields are mandatory");
            saveSuccessful = false;
        }
        else {
//            if (jTxtDestination.getText().matches("^[0-9]\\d*$")){
//                JOptionPane.showMessageDialog(null, "Destination must be a valid string value");
//                saveSuccessful = false;
//            }
//            else if(Integer.parseInt(jTxtDestination.getText()) <=0 ){
//                JOptionPane.showMessageDialog(null, "Passenger capacity cannot be 0 or less than 0");
//                saveSuccessful = false;
//            }
//
//            if (!jTxtSource.getText().matches("^[0-9]\\d*$")){
//                JOptionPane.showMessageDialog(null, "Enter a valid value for serial number");
//                saveSuccessful = false;
//            }
//            else if(Integer.parseInt(jTxtSource.getText()) <=0 ){
//                JOptionPane.showMessageDialog(null, "Serial number cannot be 0 or less than 0");
//                saveSuccessful = false;
//            }
//
//            if (!jTxtDepartureDate.getText().isEmpty()){
//                if(!jTxtDepartureDate.getText().matches("^[1-9]\\d*(\\.\\d+)?$")){
//                    JOptionPane.showMessageDialog(null, "Fuel Consumption value is invalid");
//                    saveSuccessful = false;
//                }
//            }

        }
        if(saveSuccessful){
            flight.setFlightNumber(jTxtFlightNo.getText());
            flight.setSource(jTxtSource.getText());
            flight.setDestination(jTxtDestination.getText());
            flight.setArrivalDate(jTxtArrivalDate.getText());
            flight.setArrivalTime(jTxtArrivalTime.getText());
            flight.setDepartureDate(jTxtDepartureDate.getText());
            flight.setDepartureTime(jTxtDepartureTime.getText());
            flight.setSeatsAvailable(new Seat[size][size]);
            JOptionPane.showMessageDialog(null, "Flight created successfully");
            //seatAllocation(flight);
            //clearFields();
        }
        else{
             flightSchedule.deleteFlight(flight);
        }
    }//GEN-LAST:event_jBtnSaveActionPerformed
    
     private void seatAllocation(Flight flight)
    {
        Seat seats[][] = flight.getSeatsAvailable();
        int totalSeats=0;
        
        for(int i=0;i<seats.length;i++)
        {
            for(int j=0;j<seats[0].length;j++)
            {
                seats[i][j] = new Seat();
                switch(j)
                {
                    case 0:
                        seats[i][j].setSeatRow(i+1);
                        seats[i][j].setSeatColumn("A");
                        seats[i][j].setSeatPrice(500);
                        seats[i][j].setSeatType("Window");
                        seats[i][j].setBookingStatus(false);
                        seats[i][j].setSeatAlloted(seats[i][j].getSeatRow()+seats[i][j].getSeatColumn());
                        totalSeats++;
                        break;
                    case 1:
                        seats[i][j].setSeatRow(i+1);
                        seats[i][j].setSeatColumn("B");
                        seats[i][j].setSeatPrice(400);
                        seats[i][j].setSeatType("Middle");
                        seats[i][j].setBookingStatus(false);
                        seats[i][j].setSeatAlloted(seats[i][j].getSeatRow()+seats[i][j].getSeatColumn());
                        totalSeats++;
                        break;
                    case 2:
                        seats[i][j].setSeatRow(i+1);
                        seats[i][j].setSeatColumn("C");
                        seats[i][j].setSeatPrice(300);
                        seats[i][j].setSeatType("Aisle");
                        seats[i][j].setBookingStatus(false);
                        seats[i][j].setSeatAlloted(seats[i][j].getSeatRow()+seats[i][j].getSeatColumn());
                        totalSeats++;
                        break;
                    case 3:
                        seats[i][j].setSeatRow(i+1);
                        seats[i][j].setSeatColumn("D");
                        seats[i][j].setSeatPrice(300);
                        seats[i][j].setSeatType("Aisle");
                        seats[i][j].setBookingStatus(false);
                        seats[i][j].setSeatAlloted(seats[i][j].getSeatRow()+seats[i][j].getSeatColumn());
                        totalSeats++;
                        break;
                    case 4:
                        seats[i][j].setSeatRow(i+1);
                        seats[i][j].setSeatColumn("E");
                        seats[i][j].setSeatPrice(400);
                        seats[i][j].setSeatType("Middle");
                        seats[i][j].setBookingStatus(false);
                        seats[i][j].setSeatAlloted(seats[i][j].getSeatRow()+seats[i][j].getSeatColumn());
                        totalSeats++;
                        break;
                    case 5:
                        seats[i][j].setSeatRow(i+1);    
                        seats[i][j].setSeatColumn("F");
                        seats[i][j].setSeatPrice(500);
                        seats[i][j].setSeatType("Window");
                        seats[i][j].setBookingStatus(false);
                        seats[i][j].setSeatAlloted(seats[i][j].getSeatRow()+seats[i][j].getSeatColumn());
                        totalSeats++;
                        break;
                } 
            }
        }
        flight.setTotalSeats(totalSeats);
        flight.setSeatsRemaining(totalSeats);
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        layout.previous(CardSequenceJPanel);

        Component components[] = CardSequenceJPanel.getComponents();
        for (Component component : components) {
            if (component instanceof ManageFlightsJPanel) {
                ManageFlightsJPanel mPanel = (ManageFlightsJPanel) component;
                mPanel.populateJTable();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtArrivalDate;
    private javax.swing.JTextField jTxtArrivalTime;
    private javax.swing.JTextField jTxtDepartureDate;
    private javax.swing.JTextField jTxtDepartureTime;
    private javax.swing.JTextField jTxtDestination;
    private javax.swing.JTextField jTxtFlightNo;
    private javax.swing.JTextField jTxtSource;
    private javax.swing.JTextField jTxtTotalSeats;
    // End of variables declaration//GEN-END:variables
}
