/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageAirliners.ManageFlightSchedules;

import business.AirLiner;
import business.Airplane;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.ManageAirliners.ManageAirlinerJPanel;

/**
 *
 * @author Sweta Chowdhury
 */
public class CreateAirplaneJPanel extends javax.swing.JPanel {

    private JPanel CardSequenceJPanel;
    private AirLiner airliner;
    private CardLayout layout;
    private TravelAgency travelAgency;
    /**
     * Creates new form CreateAirplaneJPanel
     */
    public CreateAirplaneJPanel(JPanel CardSequenceJPanel, TravelAgency travelAgency, AirLiner airliner) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airliner = airliner;
        layout = (CardLayout) CardSequenceJPanel.getLayout();
        this.travelAgency = travelAgency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtAirplaneName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtSerialNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtModelNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtPassCapacity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtFuelConsumption = new javax.swing.JTextField();
        jBtnSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("Aircraft Type            *");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Create Airplane");

        jLabel4.setText("Serial Number           *");

        jLabel3.setText("Model Number          *");

        jLabel5.setText("Fuel Consumption   ");

        jLabel6.setText("Passenger Capacity    *");

        jBtnSave.setText("Save");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtModelNum)
                                    .addComponent(jTxtAirplaneName)
                                    .addComponent(jTxtSerialNum)
                                    .addComponent(jTxtPassCapacity)
                                    .addComponent(jTxtFuelConsumption)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(336, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jTxtAirplaneName, jTxtModelNum, jTxtSerialNum});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTxtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPassCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFuelConsumption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jTxtAirplaneName, jTxtModelNum, jTxtSerialNum});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, jTxtFuelConsumption, jTxtPassCapacity});

    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        // TODO add your handling code here:
        Boolean saveSuccessful = true;
        Airplane airplane = airliner.addAirplane();       
        if (jTxtAirplaneName.getText().isEmpty() || jTxtSerialNum.getText().isEmpty() || jTxtModelNum.getText().isEmpty() || jTxtPassCapacity.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All (*) marked fields are mandatory");    
            saveSuccessful = false;
        }          
        else {         
            if (!jTxtPassCapacity.getText().matches("^[0-9]\\d*$")){
                JOptionPane.showMessageDialog(null, "Enter a valid value for passenger capacity");
                 saveSuccessful = false;
            }
            else if(Integer.parseInt(jTxtPassCapacity.getText()) <=0 ){
                JOptionPane.showMessageDialog(null, "Passenger capacity cannot be 0 or less than 0");
                 saveSuccessful = false;
            }
            
            if (!jTxtSerialNum.getText().matches("^[0-9]\\d*$")){
                JOptionPane.showMessageDialog(null, "Enter a valid value for serial number");
                 saveSuccessful = false;
            }
            else if(Integer.parseInt(jTxtSerialNum.getText()) <=0 ){
                 JOptionPane.showMessageDialog(null, "Serial number cannot be 0 or less than 0");
                 saveSuccessful = false;
            }
            
            if (!jTxtFuelConsumption.getText().isEmpty()){
                if(!jTxtFuelConsumption.getText().matches("^[1-9]\\d*(\\.\\d+)?$")){
                    JOptionPane.showMessageDialog(null, "Fuel Consumption value is invalid");
                    saveSuccessful = false;
                }
            }
            
        }
        
        if(saveSuccessful){
            airplane.setAirPlaneName(jTxtAirplaneName.getText());
            airplane.setSerialNum(Long.parseLong(jTxtSerialNum.getText()) );
            airplane.setModelNum(jTxtModelNum.getText());
            airplane.setPassengerCapacity(Integer.parseInt(jTxtPassCapacity.getText()));
            airplane.setFuelConsumption(Double.parseDouble(jTxtFuelConsumption.getText()));
            JOptionPane.showMessageDialog(null, "Airplane created successfully");
            clearFields();
        }
        else{
            airliner.deleteAirplane(airplane);
        } 
        
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        layout.previous(CardSequenceJPanel);

        Component components[] = CardSequenceJPanel.getComponents();
        for (Component component : components) {
            if (component instanceof ManageAirplaneJPanel) {
                ManageAirplaneJPanel mPanel = (ManageAirplaneJPanel) component;
                mPanel.populateJTable();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void clearFields(){
        jTxtAirplaneName.setText("");
        jTxtSerialNum.setText("");
        jTxtModelNum.setText("");
        jTxtPassCapacity.setText("");
        jTxtFuelConsumption.setText("");       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTxtAirplaneName;
    private javax.swing.JTextField jTxtFuelConsumption;
    private javax.swing.JTextField jTxtModelNum;
    private javax.swing.JTextField jTxtPassCapacity;
    private javax.swing.JTextField jTxtSerialNum;
    // End of variables declaration//GEN-END:variables
}
