/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageAirliners.ManageFlightSchedules;

import business.AirLiner;
import business.Airplane;
import business.Flight;
import business.FlightSchedule;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sweta Chowdhury
 */
public class ManageFlightsJPanel extends javax.swing.JPanel {
    private JPanel CardSequenceJPanel;
    private AirLiner airliner;
    private CardLayout layout;
    private TravelAgency travelAgency;
    private Airplane airplane;
    /**
     * Creates new form ManageFlightsJPanel
     */
    public ManageFlightsJPanel(JPanel CardSequenceJPanel, TravelAgency travelAgency, AirLiner airliner, Airplane airplane) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airliner = airliner;
        this.airplane = airplane;
        layout = (CardLayout) CardSequenceJPanel.getLayout();
        jLblHeader.setText(jLblHeader.getText()+ " " + airplane.getAirPlaneName());
        this.travelAgency = travelAgency;
        populateJTable();
    }

     public void populateJTable(){
        DefaultTableModel defaultTM = (DefaultTableModel) jFlightSchedule.getModel();
        defaultTM.setRowCount(0);
        
        
        for(Flight flight : airplane.getFlightSchedule().getFlightCatalog()){
            Object row[] = new Object[jFlightSchedule.getColumnCount()];
            row[0] = flight;
            row[1] = flight.getSource();
            row[2] = flight.getDestination();
            row[3] = flight.getDepartureDate() + " " + flight.getDepartureTime();
            row[4] = flight.getArrivalDate()+ " " + flight.getArrivalTime();
            row[5] = flight.getSeatsRemaining();
            defaultTM.addRow(row);
        }
        
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jFlightSchedule = new javax.swing.JTable();
        jBtnAddFlight = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jBtnViewFlight = new javax.swing.JButton();

        jLblHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLblHeader.setText("Manage Flights for ");

        jFlightSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Source", "Destination", "Departure Date and Time", "Arrival Date and Time", "Seats Remaining"
            }
        ));
        jScrollPane1.setViewportView(jFlightSchedule);

        jBtnAddFlight.setText("New Flight");
        jBtnAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddFlightActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel Flights");

        jBtnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnBack.setText("<< Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jBtnViewFlight.setText("View Flight");
        jBtnViewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnViewFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jBtnAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jBtnViewFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAddFlight)
                    .addComponent(jButton2)
                    .addComponent(jBtnViewFlight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddFlightActionPerformed
        // TODO add your handling code here:
         CreateFlightJPanel cFlight = new CreateFlightJPanel(CardSequenceJPanel, travelAgency, airliner, airplane);
         CardSequenceJPanel.add("CreatFlightPanel", cFlight);
         layout.next(CardSequenceJPanel);
        
    }//GEN-LAST:event_jBtnAddFlightActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        layout.previous(CardSequenceJPanel);

        Component components[] = CardSequenceJPanel.getComponents();
        for (Component component : components) {
            if (component instanceof ManageAirplaneJPanel) {
                ManageAirplaneJPanel mPanel = (ManageAirplaneJPanel) component;
                mPanel.populateJTable();
            }
        }
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnViewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnViewFlightActionPerformed
        // TODO add your handling code here:
        Flight selectedFlight;
        int selectedRow = jFlightSchedule.getSelectedRow();
        if (selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Please select a flight");
        }
        else{
            selectedFlight = (Flight) jFlightSchedule.getValueAt(selectedRow, 0);
            ViewFlightJPanel viewFlightPanel = new ViewFlightJPanel(CardSequenceJPanel, selectedFlight);
            CardSequenceJPanel.add("ViewFlightPanel", viewFlightPanel);
            layout.next(CardSequenceJPanel);           
        }
               
    }//GEN-LAST:event_jBtnViewFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddFlight;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnViewFlight;
    private javax.swing.JButton jButton2;
    private javax.swing.JTable jFlightSchedule;
    private javax.swing.JLabel jLblHeader;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
