/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageAirliners.ManageFlightSchedules;

import business.AirLiner;
import business.Airplane;
import business.Flight;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sweta Chowdhury
 */
public class ManageFlightSchedulesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFlightSchedulesJPanel
     */
    private CardLayout layout;
    private JPanel CardSequenceJPanel;
    private TravelAgency travelAgency;
    private AirLiner airliner;
    public ManageFlightSchedulesJPanel(JPanel CardSequenceJPanel,TravelAgency travelAgency, AirLiner airliner) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.travelAgency = travelAgency;
        this.airliner = airliner;
        layout = (CardLayout) CardSequenceJPanel.getLayout();
        jLabelHeader.setText(jLabelHeader.getText() + " " + airliner.getAirLinerName());
        populateJTable();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnManageAirplane = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblFlightSchedules = new javax.swing.JTable();
        jLabelHeader = new javax.swing.JLabel();
        jBtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jBtnManageAirplane.setText("Manage Airplanes");
        jBtnManageAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnManageAirplaneActionPerformed(evt);
            }
        });

        jTblFlightSchedules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Name", "Flight Number", "Source", "Destination", "Departure Date and Time", "Arrival Date and Time"
            }
        ));
        jScrollPane1.setViewportView(jTblFlightSchedules);

        jLabelHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelHeader.setText("Manage Flight Schedules for");

        jBtnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnBack.setText("<< Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Flight Schedule");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnManageAirplane))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jBtnManageAirplane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void populateJTable(){
        DefaultTableModel dtm = (DefaultTableModel) jTblFlightSchedules.getModel();
        dtm.setRowCount(0);
        
        for(Airplane airplane: airliner.getAirplaneCatalog()){
            for(Flight flight : airplane.getFlightSchedule().getFlightCatalog()){
                Object row[] = new Object[jTblFlightSchedules.getColumnCount()];
                row[0] = airplane.getAirPlaneName();
                row[1] = flight.getFlightNumber();
                row[2] = flight.getSource();
                row[3] = flight.getDestination() ;
                row[4] = flight.getDepartureDate() + " " + flight.getDepartureTime();
                row[5] = flight.getArrivalDate()+ " " + flight.getArrivalTime();
                dtm.addRow(row);
            }
        }       
    }
    
    private void jBtnManageAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnManageAirplaneActionPerformed
        // TODO add your handling code here:
        ManageAirplaneJPanel manageAirplane = new ManageAirplaneJPanel(CardSequenceJPanel, travelAgency, airliner);
        CardSequenceJPanel.add(manageAirplane);
        layout.next(CardSequenceJPanel);
        
    }//GEN-LAST:event_jBtnManageAirplaneActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        layout.previous(CardSequenceJPanel);

        Component components[] = CardSequenceJPanel.getComponents();
        for (Component component : components) {
            if (component instanceof ManageAirplaneJPanel) {
                ManageAirplaneJPanel mPanel = (ManageAirplaneJPanel) component;
                mPanel.populateJTable();
            }
        }
    }//GEN-LAST:event_jBtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnManageAirplane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblFlightSchedules;
    // End of variables declaration//GEN-END:variables
}
