/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageAirliners.ManageFlightSchedules;

import business.AirLiner;
import business.Airplane;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sweta Chowdhury
 */
public class ManageAirplaneJPanel extends javax.swing.JPanel {
    private JPanel CardSequenceJPanel;
    private AirLiner airliner;
    private CardLayout layout;
    private TravelAgency travelAgency;
    /**
     * Creates new form ManageAirplaneJPanel
     */
    public ManageAirplaneJPanel(JPanel CardSequenceJPanel, TravelAgency travelAgency, AirLiner airliner) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airliner = airliner;
        layout = (CardLayout) CardSequenceJPanel.getLayout();
        jLabelHeader.setText(jLabelHeader.getText()+ " " + airliner.getAirLinerName());
        this.travelAgency = travelAgency;
        populateJTable();
    }

    public void populateJTable(){
        DefaultTableModel defaultTM = (DefaultTableModel) jTblAirplanes.getModel();
        defaultTM.setRowCount(0);
        for (Airplane airplane : airliner.getAirplaneCatalog()){
            Object row[] = new Object[jTblAirplanes.getColumnCount()];
            row[0] = airplane;
            row[1] = airplane.getModelNum();
            row[2] = airplane.getSerialNum();
            row[3] = airplane.getPassengerCapacity();
            defaultTM.addRow(row);
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblAirplanes = new javax.swing.JTable();
        jBtnCreateAirliner = new javax.swing.JButton();
        jBtnViewPlane = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jBtnManageFlights = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();

        jLabelHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelHeader.setText("Manage Airplanes for");

        jTblAirplanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Name", "Model Num", "Serial Num", "Passenger Capacity"
            }
        ));
        jScrollPane1.setViewportView(jTblAirplanes);

        jBtnCreateAirliner.setText("New Airplane");
        jBtnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCreateAirlinerActionPerformed(evt);
            }
        });

        jBtnViewPlane.setText("View Airplane");
        jBtnViewPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnViewPlaneActionPerformed(evt);
            }
        });

        jBtnDelete.setText("Delete Airplane");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jBtnManageFlights.setText("Manage Flights");
        jBtnManageFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnManageFlightsActionPerformed(evt);
            }
        });

        jBtnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnBack.setText("<< Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jBtnCreateAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jBtnViewPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnManageFlights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCreateAirliner)
                    .addComponent(jBtnViewPlane)
                    .addComponent(jBtnDelete))
                .addGap(42, 42, 42)
                .addComponent(jBtnManageFlights)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCreateAirlinerActionPerformed
        // TODO add your handling code here:
        CreateAirplaneJPanel createAirplanePanel = new CreateAirplaneJPanel(CardSequenceJPanel, travelAgency, airliner);
        CardSequenceJPanel.add("CreateAirplanePanel", createAirplanePanel);
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_jBtnCreateAirlinerActionPerformed

    private void jBtnViewPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnViewPlaneActionPerformed
        // TODO add your handling code here:
        Airplane selectedAirplane;
        int selectedRow =  jTblAirplanes.getSelectedRow();

        if(selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Please select an airliner");
        }
        else{
            selectedAirplane = (Airplane) jTblAirplanes.getValueAt(jTblAirplanes.getSelectedRow(), 0);
            ViewAirplaneJPanel viewAirplanePanel = new ViewAirplaneJPanel(CardSequenceJPanel, travelAgency, airliner, selectedAirplane);
            CardSequenceJPanel.add("ViewAirplaneJPanel", viewAirplanePanel);
            layout.next(CardSequenceJPanel);

        }

    }//GEN-LAST:event_jBtnViewPlaneActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        // TODO add your handling code here:
       Airplane selectedAirplane;
        int selectedRow =  jTblAirplanes.getSelectedRow();

       if(selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Please select an airplane");
       }
        else{
           selectedAirplane = (Airplane) jTblAirplanes.getValueAt(jTblAirplanes.getSelectedRow(), 0);
           airliner.deleteAirplane(selectedAirplane);
           populateJTable();
        }
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnManageFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnManageFlightsActionPerformed
        // TODO add your handling code here:
        
       Airplane selectedAirplane;
       int selectedRow =  jTblAirplanes.getSelectedRow();

       if(selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Please select an airplane");
       }
        else{
           selectedAirplane = (Airplane) jTblAirplanes.getValueAt(jTblAirplanes.getSelectedRow(), 0);
           ManageFlightsJPanel mFlight = new ManageFlightsJPanel(CardSequenceJPanel, travelAgency, airliner, selectedAirplane);
           CardSequenceJPanel.add("ManageFlights", mFlight);
           layout.next(CardSequenceJPanel);
       }
        
       
        
        
    }//GEN-LAST:event_jBtnManageFlightsActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        layout.previous(CardSequenceJPanel);
        
        
        Component components[] = CardSequenceJPanel.getComponents();
        for (Component component : components) {
            if (component instanceof ManageFlightSchedulesJPanel) {
                ManageFlightSchedulesJPanel mPanel = (ManageFlightSchedulesJPanel) component;
                mPanel.populateJTable();
            }
        }

    }//GEN-LAST:event_jBtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnCreateAirliner;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnManageFlights;
    private javax.swing.JButton jBtnViewPlane;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblAirplanes;
    // End of variables declaration//GEN-END:variables
}
