/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageAirliners.ManageFlightSchedules;

import business.AirLiner;
import business.Airplane;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.ManageAirliners.ManageFlightSchedules.ManageAirplaneJPanel;

/**
 *
 * @author Sweta Chowdhury
 */
public class ViewAirplaneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirplaneJPanel
     */
    
    private JPanel CardSequenceJPanel;
    private AirLiner airliner;
    private Airplane airplane;
    private CardLayout layout;
    private TravelAgency travelAgency;
    
    public ViewAirplaneJPanel(JPanel CardSequenceJPanel, TravelAgency travelAgency, AirLiner airliner, Airplane airplane) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airliner = airliner;
        this.airplane = airplane;
        layout = (CardLayout) CardSequenceJPanel.getLayout();
        this.travelAgency = travelAgency;
        populateFields();
    }

     public void populateFields() {
        jTxtAirplaneName.setText(airplane.getAirPlaneName());
        jTxtSerialNum.setText(Long.toString(airplane.getSerialNum()));
        jTxtModelNum.setText(airplane.getModelNum());
        jTxtPassCapacity.setText(Integer.toString(airplane.getPassengerCapacity()));
        jTxtFuelConsumption.setText(Double.toString(airplane.getFuelConsumption()));
    }
     
     public void enableDisableFields(Boolean value) {
        jTxtAirplaneName.setEditable(value);
        jTxtSerialNum.setEditable(value);
        jTxtModelNum.setEditable(value);
        jTxtPassCapacity.setEditable(value);
        jTxtFuelConsumption.setEditable(value);
        jBtnSave.setEnabled(value);
        jBtnUpdate.setEnabled(!value);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTxtAirplaneName = new javax.swing.JTextField();
        jTxtFuelConsumption = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnSave = new javax.swing.JButton();
        jTxtPassCapacity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtSerialNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtModelNum = new javax.swing.JTextField();
        jBtnBack = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();

        jLabel6.setText("Passenger Capacity     *");

        jTxtAirplaneName.setEditable(false);

        jTxtFuelConsumption.setEditable(false);

        jLabel2.setText("Airplane Name          *");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("View Airplane");

        jLabel4.setText("Serial Number           *");

        jBtnSave.setText("Save");
        jBtnSave.setEnabled(false);
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jTxtPassCapacity.setEditable(false);

        jLabel3.setText("Total Seats                *");

        jTxtSerialNum.setEditable(false);

        jLabel5.setText("Fuel Consumption   ");

        jTxtModelNum.setEditable(false);

        jBtnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnBack.setText("<< Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jBtnUpdate.setText("Update");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(325, 325, 325))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(113, 113, 113)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtAirplaneName)
                                .addComponent(jTxtModelNum)
                                .addComponent(jTxtSerialNum)
                                .addComponent(jTxtPassCapacity)
                                .addComponent(jTxtFuelConsumption))))
                    .addContainerGap(287, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jTxtAirplaneName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(66, 66, 66)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jTxtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTxtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addComponent(jTxtPassCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)
                    .addComponent(jTxtFuelConsumption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(222, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jTxtAirplaneName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6, jTxtFuelConsumption, jTxtModelNum, jTxtPassCapacity, jTxtSerialNum});

    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        // TODO add your handling code here:
        Boolean saveSuccessful = true;
        enableDisableFields(false);
        if (jTxtAirplaneName.getText().isEmpty() || jTxtSerialNum.getText().isEmpty() || jTxtModelNum.getText().isEmpty() || jTxtPassCapacity.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All (*) marked fields are mandatory");
            saveSuccessful = false;
        }
        else {
            if (!jTxtPassCapacity.getText().matches("^[0-9]\\d*$")){
                JOptionPane.showMessageDialog(null, "Enter a valid value for passenger capacity");
                saveSuccessful = false;
            }
            else if(Integer.parseInt(jTxtPassCapacity.getText()) <=0 ){
                JOptionPane.showMessageDialog(null, "Passenger capacity cannot be 0 or less than 0");
                saveSuccessful = false;
            }

            if (!jTxtSerialNum.getText().matches("^[0-9]\\d*$")){
                JOptionPane.showMessageDialog(null, "Enter a valid value for serial number");
                saveSuccessful = false;
            }
            else if(Integer.parseInt(jTxtSerialNum.getText()) <=0 ){
                JOptionPane.showMessageDialog(null, "Serial number cannot be 0 or less than 0");
                saveSuccessful = false;
            }

            if (!jTxtFuelConsumption.getText().isEmpty()){
                if(!jTxtFuelConsumption.getText().matches("^[1-9]\\d*(\\.\\d+)?$")){
                    JOptionPane.showMessageDialog(null, "Fuel Consumption value is invalid");
                    saveSuccessful = false;
                }
            }
        }

        if(saveSuccessful){
            airplane.setAirPlaneName(jTxtAirplaneName.getText());
            airplane.setSerialNum(Long.parseLong(jTxtSerialNum.getText()) );
            airplane.setModelNum(jTxtModelNum.getText());
            airplane.setPassengerCapacity(Integer.parseInt(jTxtPassCapacity.getText()));
            airplane.setFuelConsumption(Double.parseDouble(jTxtFuelConsumption.getText()));
            JOptionPane.showMessageDialog(null, "Airplane updated successfully");
        }
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        layout.previous(CardSequenceJPanel);

        Component components[] = CardSequenceJPanel.getComponents();
        for (Component component : components) {
            if (component instanceof ManageAirplaneJPanel) {
                ManageAirplaneJPanel mPanel = (ManageAirplaneJPanel) component;
                mPanel.populateJTable();
            }
        }
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        // TODO add your handling code here:
        enableDisableFields(true);
    }//GEN-LAST:event_jBtnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTxtAirplaneName;
    private javax.swing.JTextField jTxtFuelConsumption;
    private javax.swing.JTextField jTxtModelNum;
    private javax.swing.JTextField jTxtPassCapacity;
    private javax.swing.JTextField jTxtSerialNum;
    // End of variables declaration//GEN-END:variables
}
