/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageAirliners;

import business.AirLiner;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sweta Chowdhury
 */
public class CreateNewAirlineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirlineJPanel
     */
    private CardLayout layout;
    private JPanel CardSequenceJPanel;
    private TravelAgency travelAgency;
    public CreateNewAirlineJPanel(JPanel CardSequenceJPanel, TravelAgency travelAgency ) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        layout = (CardLayout) CardSequenceJPanel.getLayout();
        this.travelAgency = travelAgency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtAirlinerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtAirlinerOwner = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtEstdDate = new javax.swing.JTextField();
        jBtnSave = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Create Airliner");

        jLabel2.setText("Airline Name    *");

        jLabel3.setText("Owned By        *   ");

        jLabel4.setText("Established On");

        jBtnSave.setText("Save");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jBtnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnBack.setText("<< Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtAirlinerOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEstdDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jTxtAirlinerName, jTxtAirlinerOwner, jTxtEstdDate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTxtAirlinerOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtEstdDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jTxtAirlinerName, jTxtAirlinerOwner, jTxtEstdDate});

    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        // TODO add your handling code here:
        
        Boolean saveSuccessful = true;
        AirLiner airliner = travelAgency.addAirliner();       
        if (jTxtAirlinerName.getText().isEmpty() || jTxtAirlinerOwner.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All (*) marked fields are mandatory");    
            saveSuccessful = false;
        }          
        else if(!jTxtEstdDate.getText().isEmpty()){
            if(jTxtEstdDate.getText().matches("^((0|1)\\d{1})-((0|1|2)\\d{1})-((19|20)\\d{2})"))
                 airliner.setEstablishmentDate(jTxtEstdDate.getText());
            else{
                JOptionPane.showMessageDialog(null, "Date must be in MM-DD-YYYY format");
                saveSuccessful = false;
            } 
            airliner.setAirLinerName(jTxtAirlinerName.getText());
            airliner.setManufacturer(jTxtAirlinerOwner.getText());
        }
        
        if(saveSuccessful){
            JOptionPane.showMessageDialog(null, "Airliner created successfully");
            clearFields();
        }
        else{
            travelAgency.deleteAirliner(airliner);
        } 
        
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        layout.previous(CardSequenceJPanel);
        
        Component components[] = CardSequenceJPanel.getComponents();    
        for(Component component: components){
            if (component instanceof ManageAirlinerJPanel){
                ManageAirlinerJPanel mPanel = (ManageAirlinerJPanel)component;
                mPanel.populateAirLinerTable();
            }
                
        }
        
    }//GEN-LAST:event_jBtnBackActionPerformed

    public void clearFields(){
        jTxtAirlinerName.setText("");
        jTxtAirlinerOwner.setText("");
        jTxtEstdDate.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtAirlinerName;
    private javax.swing.JTextField jTxtAirlinerOwner;
    private javax.swing.JTextField jTxtEstdDate;
    // End of variables declaration//GEN-END:variables
}
