/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageAirliners;

import business.AirLiner;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sweta Chowdhury
 */
public class ViewAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirlinerJPanel
     */
    private CardLayout layout;
    private JPanel CardSequenceJPanel;
    private TravelAgency travelAgency;
    private AirLiner airliner;

    public ViewAirlinerJPanel(JPanel CardSequenceJPanel, TravelAgency travelAgency, AirLiner airliner) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        layout = (CardLayout) CardSequenceJPanel.getLayout();
        this.travelAgency = travelAgency;
        this.airliner = airliner;
        populateFields();
    }

    public void populateFields() {
        jTxtAirlinerName.setText(airliner.getAirLinerName());
        jTxtAirlinerOwner.setText(airliner.getManufacturer());
        jTxtEstdDate.setText(airliner.getEstablishmentDate());      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtAirlinerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtAirlinerOwner = new javax.swing.JTextField();
        jTxtEstdDate = new javax.swing.JTextField();
        jBtnSave = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Create Airliner");

        jLabel2.setText("Airline Name    *");

        jLabel3.setText("Owned By        *   ");

        jTxtAirlinerName.setEditable(false);

        jLabel4.setText("Established On");

        jTxtAirlinerOwner.setEditable(false);

        jTxtEstdDate.setEditable(false);

        jBtnSave.setText("Save");
        jBtnSave.setEnabled(false);
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jBtnUpdate.setText("Update");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jBtnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnBack.setText("<< Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("View Airliner");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtAirlinerName, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(jTxtAirlinerOwner)
                            .addComponent(jTxtEstdDate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jTxtAirlinerName, jTxtAirlinerOwner, jTxtEstdDate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTxtAirlinerOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtEstdDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jBtnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jTxtAirlinerName, jTxtAirlinerOwner, jTxtEstdDate});

    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        // TODO add your handling code here:
        enableDisableFields(false);
        Boolean saveSuccessful = true;
        if (jTxtAirlinerName.getText().isEmpty() || jTxtAirlinerOwner.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All (*) marked fields are mandatory");
            saveSuccessful = false;
        } else if (!jTxtEstdDate.getText().isEmpty()) {
            if (!jTxtEstdDate.getText().matches("^((0|1)\\d{1})-((0|1|2)\\d{1})-((19|20)\\d{2})")) {
                JOptionPane.showMessageDialog(null, "Date must be in MM-DD-YYYY format");
                saveSuccessful = false;
            }
        }

        if (saveSuccessful) {
            airliner.setAirLinerName(jTxtAirlinerName.getText());
            airliner.setManufacturer(jTxtAirlinerOwner.getText());
            airliner.setEstablishmentDate(jTxtEstdDate.getText());
            JOptionPane.showMessageDialog(null, "Airliner updated successfully");
        }

    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        layout.previous(CardSequenceJPanel);

        Component components[] = CardSequenceJPanel.getComponents();
        for (Component component : components) {
            if (component instanceof ManageAirlinerJPanel) {
                ManageAirlinerJPanel mPanel = (ManageAirlinerJPanel) component;
                mPanel.populateAirLinerTable();
            }
        }

    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        // TODO add your handling code here:
        enableDisableFields(true);
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    public void enableDisableFields(Boolean value) {
        jTxtAirlinerName.setEditable(value);
        jTxtAirlinerOwner.setEditable(value);
        jTxtEstdDate.setEditable(value);
        jBtnSave.setEnabled(value);
        jBtnUpdate.setEnabled(!value);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTxtAirlinerName;
    private javax.swing.JTextField jTxtAirlinerOwner;
    private javax.swing.JTextField jTxtEstdDate;
    // End of variables declaration//GEN-END:variables
}
