/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.AirLiner;
import business.Airplane;
import business.Flight;
import business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.ManageAirliners.ManageAirlinerJPanel;

/**
 *
 * @author Sweta Chowdhury
 */
public class TravelAgencyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelAgencyJPanel
     */
    private CardLayout layout;
    private JPanel CardSequenceJPanel;
    private TravelAgency travelAgency;
    public TravelAgencyJPanel(JPanel CardSequenceJPanel, TravelAgency travelAgency) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.travelAgency = travelAgency;
        layout = (CardLayout) CardSequenceJPanel.getLayout();       
        populateJPanel();
    }
    
    public void populateJPanel(){
        
        DefaultTableModel dtm = (DefaultTableModel) jTblMasterSchedule.getModel();
        dtm.setRowCount(0);
        
        for (AirLiner airliner : travelAgency.getAirlinerCatalog()) {
            for (Airplane airplane : airliner.getAirplaneCatalog()) {
                for (Flight flight : airplane.getFlightSchedule().getFlightCatalog()) {
                    Object row[] = new Object[jTblMasterSchedule.getColumnCount()];
                    row[0] = airliner.getAirLinerName();
                    row[1] = airplane.getAirPlaneName();
                    row[2] = flight.getFlightNumber();
                    row[3] = flight.getSource();
                    row[4] = flight.getDestination();                
                    dtm.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnManageAirliner = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblMasterSchedule = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jBtnManageAirliner.setText("Manage Airliner");
        jBtnManageAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnManageAirlinerActionPerformed(evt);
            }
        });

        jTblMasterSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner", "Aircraft Type", "Flight Number", "Source", "Destination"
            }
        ));
        jScrollPane1.setViewportView(jTblMasterSchedule);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Travel Agency");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnManageAirliner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBtnManageAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnManageAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnManageAirlinerActionPerformed
        // TODO add your handling code here:
        ManageAirlinerJPanel manageAirlinerPanel = new ManageAirlinerJPanel(CardSequenceJPanel, travelAgency);
        CardSequenceJPanel.add("ManageAirLiner", manageAirlinerPanel);
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_jBtnManageAirlinerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnManageAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblMasterSchedule;
    // End of variables declaration//GEN-END:variables
}
